# Generated by Django 5.2 on 2025-04-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField()),
                ('locla', models.CharField(max_length=150)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/%d/')),
            ],
        ),
    ]
