# Generated by Django 5.2 on 2025-04-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='locla',
            new_name='local',
        ),
        migrations.AddField(
            model_name='eventos',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
