# Generated by Django 5.2 on 2025-04-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_rename_locla_eventos_local_eventos_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='legenda',
            field=models.CharField(default='', max_length=150),
        ),
    ]
