# Generated by Django 5.2 on 2025-04-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_eventos_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='destque',
            field=models.BooleanField(default=False),
        ),
    ]
