# Generated by Django 5.2 on 2025-04-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_eventos_destque'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
