# Generated by Django 5.2 on 2025-04-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_eventos_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='destque',
            new_name='destaque',
        ),
    ]
