# Generated by Django 5.2 on 2025-04-20 20:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
