# Generated by Django 5.2 on 2025-04-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_favorito_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='favoritado',
            field=models.BooleanField(default=False),
        ),
    ]
