# Generated by Django 5.2 on 2025-04-20 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_eventos_favoritado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='eventos_favoritados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
