# Generated by Django 5.2 on 2025-04-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_eventos_favoritos_delete_favorito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='favoritado',
        ),
    ]
