# Generated by Django 5.2 on 2025-05-14 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_remove_eventos_favoritado'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='promovido_no_site',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='eventos.eventos')),
            ],
        ),
    ]
