# Generated by Django 5.2 on 2025-05-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_eventos_promovido_no_site_ingresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='quantidade_disponivel',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
