# Generated by Django 5.2 on 2025-05-13 21:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.png', max_length=255, verbose_name='imagem'),
        ),
    ]
