services:
  - type: web
    name: eventia-site
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput 
    gunicorn: setup.wsgi:application --chdir /opt/render/project/src --workers=1 --threads=2 --timeout=120 --bind 0.0.0.0:10000$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: setup.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: eventos-j4qj.onrender.com
    staticPublishPath: "/static"
    staticWebDirectory: "staticfiles"
