# Generated by Django 5.2 on 2025-05-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaPrivacidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Política de Privacidade', max_length=255)),
                ('conteudo', models.TextField()),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermosCondicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Termos e Condições de Uso', max_length=255)),
                ('conteudo', models.TextField()),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
