# Generated by Django 5.2 on 2025-05-15 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termoscondicoes',
            name='conteudo',
        ),
    ]
