# Generated by Django 5.2 on 2025-05-15 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_remove_termoscondicoes_conteudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('termos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='administracao.termoscondicoes')),
            ],
        ),
    ]
