# Generated by Django 5.2 on 2025-05-15 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0003_termoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termoscondicoes',
            name='data_atualizacao',
        ),
        migrations.AddField(
            model_name='termoscondicoes',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='termoscondicoes',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Subtopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('conteudo', models.TextField()),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopicos', to='administracao.termoscondicoes')),
            ],
        ),
        migrations.DeleteModel(
            name='TermoItem',
        ),
    ]
