# Generated by Django 5.2 on 2025-05-15 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0004_remove_termoscondicoes_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descricoes', to='administracao.termoscondicoes')),
            ],
        ),
        migrations.DeleteModel(
            name='Subtopico',
        ),
    ]
