# Generated by Django 5.2 on 2025-05-15 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0005_descricao_delete_subtopico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termoscondicoes',
            name='descricao',
        ),
        migrations.AddField(
            model_name='termoscondicoes',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TermoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('termos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='administracao.termoscondicoes')),
            ],
        ),
        migrations.AlterField(
            model_name='descricao',
            name='termo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descricoes', to='administracao.termoitem'),
        ),
    ]
