# Generated by Django 5.2 on 2025-05-15 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0006_remove_termoscondicoes_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicaprivacidade',
            name='conteudo',
        ),
        migrations.AlterField(
            model_name='politicaprivacidade',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='PoliticaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('politica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='administracao.politicaprivacidade')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticaDescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descricoes', to='administracao.politicaitem')),
            ],
        ),
    ]
