# Generated by Django 5.2 on 2025-04-21 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_remove_eventos_favoritado'),
        ('minhaArea', '0002_eventocompartilhado_mensagemgrupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemgrupo',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.eventos'),
        ),
    ]
