# Generated by Django 5.2 on 2025-04-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minhaArea', '0003_mensagemgrupo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemgrupo',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
