# Generated by Django 5.2 on 2025-05-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minhaArea', '0005_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='data_evento',
            field=models.DateField(null=True),
        ),
    ]
